# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'GoPlay' do
    
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

pod 'SVProgressHUD'
pod 'SlideMenuControllerSwift'
pod 'IQKeyboardManagerSwift', '4.0.0'
pod 'KGModal', '~> 0.0.1'


#pod 'JTCalendar', '~> 2.0'
#pod 'RDVCalendarView'
#pod 'FSCalendar'


pod 'Alamofire', '~> 3.4'
pod 'SwiftyJSON'

end

